[package]
name = "bored-node"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.34"
libp2p = { version = "0.56.0", features = ["tcp", "noise", "yamux", "tokio", "macros", "mdns", "request-response", "cbor"] }
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["full"] }
